name: kaza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  easy_localization: ^3.0.8
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^20.0.0
  google_fonts: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  timezone: ^0.10.1
  confetti: ^0.7.0
  fl_chart: ^0.70.2
  home_widget: ^0.9.0
  # New Dependencies
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  adhan: ^2.0.0+1
  pdf: ^3.11.1
  printing: ^5.13.2
  geolocator: ^14.0.2
  table_calendar: ^3.2.0
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/data/
